PY ?= python3
KAZSEARCH ?= ../kazsearch-py
APERTIUM  ?= ../apertium-kaz/apertium-kaz.kaz.lexc
KAZDICT   ?= ../kazdict/data/build/kazdict.db
KAZNLP    ?= ../kaznlp/kaznlp/morphology/mdl/sfx
KAZNERD   ?= ../KazNERD/KazNERD

.PHONY: help dict aff dic check data lexicon names names-wp paradigm paradigm-residues typos chains harmony audit audit-harmony epenthesis dist-xpi corpus residues prune negatives baseline measure scoped running dist clean

help:
	@echo "make dict      generate dict/kk_KZ.aff and dict/kk_KZ.dic"
	@echo "make check     fail if dict/kk_KZ.aff is stale"
	@echo "make measure   measure dict/ against the 2009 release"
	@echo "make baseline  measure the 2009 release on its own"
	@echo "make typos     the metric that matters: does it CATCH misspellings"
	@echo "make running   measure on real running text, weighted by word frequency"
	@echo "make paradigm  check the full nominal grid of one stem per class"
	@echo "make scoped    measure per source scope: modern, glossing, historical"
	@echo "make data      rebuild everything under data/ (needs the sources)"
	@echo "make dist      package dist/kk_KZ.oxt for LibreOffice"

# Building the dictionary needs only this repository: everything corpus-derived
# is committed under data/.
dict: aff dic

aff:
	$(PY) tools/gen_aff.py --kazsearch $(KAZSEARCH) -o dict/kk_KZ.aff

dic:
	$(PY) tools/gen_dic.py -o dict/kk_KZ.dic

check:
	$(PY) tools/gen_aff.py --kazsearch $(KAZSEARCH) --check dict/kk_KZ.aff

# Rebuilding data/ needs the corpus and the wordlist sources. The order is not
# arbitrary: residues are mined against the lexicon, and what is safe to prune
# depends on what the affix file built from those residues can regenerate.
data:
	$(MAKE) names
	$(MAKE) names-wp
	$(MAKE) lexicon
	$(MAKE) chains
	$(MAKE) residues
	$(MAKE) aff
	$(MAKE) harmony
	$(MAKE) prune
	$(MAKE) dic

lexicon:
	$(PY) tools/build_lexicon.py --apertium $(APERTIUM) --kazdict $(KAZDICT) \
		-o data/lexicon.tsv

chains:
	$(PY) tools/import_chains.py --sfx $(KAZNLP) -o data/chains.tsv

tests/corpus_cyr.txt:
	$(PY) tools/measure.py baseline/kk_KZ --kazsearch $(KAZSEARCH) >/dev/null

# Tokens with the scope of the edition they came from, so a headline number can
# mean "modern Kazakh" rather than an average over Chagatai poetry.
corpus tests/corpus.tsv:
	$(PY) tools/build_corpus.py --kazdict $(KAZDICT) -o tests/corpus.tsv

residues: tests/corpus_cyr.txt
	$(PY) tools/mine_residues.py --kazsearch $(KAZSEARCH) -o data/residues.tsv

# Corpus recall cannot tell "the language does not do this" from "the corpus
# did not happen to". The nominal and verbal grids are closed, so they can:
# every cell of one stem per class is synthesised and checked against the
# dictionary. Read-only — it writes only the tests/ reports. --voices checks
# the full verbal grid (passive, reflexive, reciprocal, causative), 11,658
# forms rather than the 2,613 of the plain grid.
paradigm:
	$(PY) tools/paradigm.py --write tests/paradigms.tsv dict/kk_KZ
	$(PY) tools/verb_paradigm.py --write tests/verb_paradigms.tsv --voices dict/kk_KZ

# The paradigm residue files data/paradigm.tsv and data/verb_paradigm.tsv are
# committed curated inputs, not regenerated by `make data`: verb_paradigm.tsv
# carries class-independent participle and gerund residues added by hand that no
# tool re-emits, so a mechanical rebuild would silently drop them and cost the
# aff its passive and causative chains. Regenerate the mechanical part alone,
# deliberately, with:  make paradigm-residues  (see the warning there).
paradigm-residues:
	@echo "WARNING: overwrites data/*paradigm.tsv with the mechanical residues"
	@echo "only; the hand-added class-independent verb residues are NOT re-emitted."
	@echo "Diff against HEAD before committing. Ctrl-C to abort." && sleep 3
	$(PY) tools/paradigm.py --residues data/paradigm.tsv dict/kk_KZ
	$(PY) tools/verb_paradigm.py --residues data/verb_paradigm.tsv --voices dict/kk_KZ

# Ask apertium-kaz's grammar about every chain the aff licenses; needs the
# `apertium` distrobox (see tools/audit_apertium.py) and a veto-free aff.
audit:
	mv -f data/apertium_veto.tsv data/apertium_veto.tsv.bak 2>/dev/null || true
	$(MAKE) aff
	$(PY) tools/audit_apertium.py --threshold 25 -o data/apertium_veto.tsv
	$(MAKE) aff

# Consonant-cluster loanword forms, generated and validated by apertium-kaz;
# needs the `apertium` distrobox.
epenthesis:
	$(PY) tools/epenthesis.py -o data/epenthesis.txt

# Vowel-harmony overrides for loanwords apertium-kaz classifies differently from
# kkphon (артиллерия is back, not front); needs the `apertium` distrobox. Merges
# into data/harmony.tsv and never overrules a harmony KazNERD attests.
audit-harmony:
	$(PY) tools/audit_harmony.py --kaznerd $(KAZNERD) -o data/harmony.tsv

# The corpus-mined half of data/harmony.tsv; overwrites the file, so re-run
# `make audit-harmony` after it to restore the apertium-driven loanword overrides
# it merges on top. `make data` runs only this half (audit-harmony needs the
# distrobox), so the committed harmony.tsv is the two merged.
harmony: tests/corpus_cyr.txt
	$(PY) tools/mine_harmony.py --kazsearch $(KAZSEARCH) --kaznerd $(KAZNERD) \
		-o data/harmony.tsv

prune: tests/corpus_cyr.txt
	$(PY) tools/prune.py --kazsearch $(KAZSEARCH) -o data/prune.txt

negatives tests/negatives.txt: tests/corpus_cyr.txt
	$(PY) tools/negatives.py tests/corpus_cyr.txt -o tests/negatives.txt

baseline: tests/negatives.txt
	$(PY) tools/measure.py baseline/kk_KZ --kazsearch $(KAZSEARCH)

# What a reader would actually see: real prose, each word weighted by how
# often it occurs, rather than a dictionary's word types counted once each.
# The test split only: names are mined from KazNERD's training split, so
# scoring on the whole corpus would be scoring on what was memorised.
# A spellchecker exists to catch mistakes. Recall says how rarely it underlines
# correct text; this says how often it does its job. The 2009 release catches
# 99.0%, and it is shown alongside because being below it is the thing to know.
typos: tests/corpus_cyr.txt
	$(PY) tools/typos.py --write tests/typos.txt dict/kk_KZ baseline/kk_KZ

running:
	$(PY) tools/measure_running.py dict/kk_KZ baseline/kk_KZ \
		--kaznerd $(KAZNERD) --split test --show-misses 10

names:
	$(PY) tools/mine_names.py --kaznerd $(KAZNERD) --kazsearch $(KAZSEARCH) \
		-o data/names.txt

# Given names and surnames from Kazakh Wikipedia, after the Statistics
# Bureau's figures. Needs network; the result is committed.
names-wp:
	$(PY) tools/fetch_names_wikipedia.py -o data/names_wp.txt

scoped: tests/corpus.tsv tests/negatives.txt
	$(PY) tools/measure.py dict/kk_KZ --against baseline/kk_KZ \
		--corpus tests/corpus.tsv --scoped

measure: tests/negatives.txt
	$(PY) tools/measure.py dict/kk_KZ --against baseline/kk_KZ --kazsearch $(KAZSEARCH)

# The same package without the kazdict-only entries: 65,298 entries instead of
# 102,034, 96.9% token coverage instead of 97.7%, and no uncleared provenance.
# This is the variant to offer upstreams that ask about licensing.
dist-clean: aff
	$(PY) tools/gen_dic.py --without kazdict -o dist/clean/kk_KZ.dic
	cp dict/kk_KZ.aff dist/clean/kk_KZ.aff

# A LibreOffice extension is a zip with the dictionary, a registration file
# telling it which locales the pair serves, and a manifest naming that file.
# Firefox and Thunderbird take dictionaries as a web extension: a manifest
# naming the locale, the pair beside it, zipped with an .xpi suffix.
dist-xpi: dict
	@rm -rf dist/xpi && mkdir -p dist/xpi/dictionaries
	cp package/xpi/manifest.json dist/xpi/
	@V=$$(grep -oP '<version value="\K[^"]+' package/description.xml); \
		sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$$V\"/" dist/xpi/manifest.json; \
		echo "stamped xpi version $$V"
	cp dict/kk_KZ.aff dist/xpi/dictionaries/kk-KZ.aff
	cp dict/kk_KZ.dic dist/xpi/dictionaries/kk-KZ.dic
	cd dist/xpi && zip -q -r ../kk_KZ.xpi . && cd ../..
	@rm -rf dist/xpi
	@ls -l dist/kk_KZ.xpi

dist: dict
	@mkdir -p dist/clean
	@rm -rf dist && mkdir -p dist/build/META-INF
	cp dict/kk_KZ.aff dict/kk_KZ.dic dist/build/
	cp package/description.xml package/dictionaries.xcu \
		package/README_kk_KZ.txt COPYING dist/build/
	cp package/META-INF/manifest.xml dist/build/META-INF/
	cd dist/build && zip -q -r ../kk_KZ.oxt . && cd ../..
	@rm -rf dist/build
	@ls -l dist/kk_KZ.oxt

clean:
	rm -rf dist tests/corpus_cyr.txt tests/corpus.tsv tests/negatives.txt __pycache__ tools/__pycache__
