"""Build the evaluation corpus from kazdict, keeping each token's source.

The corpus so far has been one blended token list, and blending is what hid two
problems. Some of its editions are not modern Kazakh at all: `Ясауи
Хикметтерінің тілі` is 12th-century Chagatai religious poetry, 41% of which a
Kazakh spellchecker should reject, and the 1966 etymological dictionary
explains itself in Russian — `вотянкого`, `обзор`, `лексики`. Scoring against
those measures nothing, and averaging them with the Academy dictionary makes a
number that cannot be acted on.

Tokens come from sense text rather than headwords, because that is where
running Kazakh is: kazdict normalises headwords hard and definitions barely at
all. Each is tagged with the scope of the edition it came from, so the same
build supports a headline number and a per-edition breakdown.

    python tools/build_corpus.py -o tests/corpus.tsv

The result is not committed: it is third-party text, and vendoring it would
attach its provenance to the dictionary's.
"""

from __future__ import annotations

import argparse
import collections
import re
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_KAZDICT = ROOT.parent / "kazdict/data/build/kazdict.db"

CYRILLIC = re.compile(r"[Ѐ-ӿ]+")

MODERN, HISTORICAL, GLOSSING = "modern", "historical", "glossing"

# Editions whose subject is a language other than modern Kazakh. Their
# rejection rates are high and *should* be: the words are Chagatai, Old Kazakh,
# Turkish or Arabic-Persian citation forms.
NOT_MODERN_KAZAKH = (
    "Ясауи Хикметтерінің тілі",
    "Әбілғазы баһадүр ханның",
    "Ескі қазақ әдеби тілінің түсіндірме сөздігі",
    "Түрік сөздігі",
    "Қазақ тіліндегі араб, парсы сөздерінің",
    "Қазақ тілінің қысқаша этимологиялық сөздігі",
)

# Editions that explain Kazakh in Russian, so their definition text is a
# mixture of the two languages and its rejections say nothing about Kazakh
# coverage.
RUSSIAN_GLOSSING = (
    "Философиялық терминдердің сөздігі",
    "Орысша-қазақша",
    "Этносаяси сөздік",
    "Алаш қозғалысы",
)


def scope_of(title: str) -> str:
    if any(title.startswith(p) for p in NOT_MODERN_KAZAKH):
        return HISTORICAL
    if any(title.startswith(p) for p in RUSSIAN_GLOSSING):
        return GLOSSING
    return MODERN


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--output", type=Path, default=ROOT / "tests/corpus.tsv")
    ap.add_argument("--kazdict", type=Path, default=DEFAULT_KAZDICT)
    ap.add_argument("--min-length", type=int, default=3,
                    help="skip shorter tokens; they are mostly particles and "
                         "single letters, and every dictionary accepts them")
    args = ap.parse_args()

    if not args.kazdict.exists():
        sys.exit(f"no kazdict database at {args.kazdict} — pass --kazdict")

    con = sqlite3.connect(f"file:{args.kazdict}?mode=ro", uri=True)
    rows = con.execute("""
        SELECT w.title, s.definition
          FROM sense s
          JOIN entry en ON en.id = s.entry_id
          JOIN edition e ON e.id = en.edition_id
          JOIN work w ON w.id = e.work_id""")

    # A token is charged to the narrowest scope it appears in, so a word the
    # Academy dictionary also uses counts as modern wherever else it turns up.
    rank = {MODERN: 0, GLOSSING: 1, HISTORICAL: 2}
    seen: dict[str, str] = {}
    for title, definition in rows:
        scope = scope_of(title)
        for token in CYRILLIC.findall(definition):
            if len(token) < args.min_length:
                continue
            current = seen.get(token)
            if current is None or rank[scope] < rank[current]:
                seen[token] = scope

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as fh:
        fh.write("# token\tscope — generated by tools/build_corpus.py\n")
        for token in sorted(seen):
            fh.write(f"{token}\t{seen[token]}\n")

    tally = collections.Counter(seen.values())
    print(f"{len(seen):,} tokens → {args.output}", file=sys.stderr)
    print("  " + "  ".join(f"{k}={v:,}" for k, v in sorted(tally.items())),
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
