"""Fold Kazakh's suffix chain into the two levels Hunspell strips.

Hunspell takes at most two suffixes off a word, and that limit is deliberate:
Németh closed hunspell#90 in 2008 saying an "affix" is meant to be an affix
*combination*, and that Hungarian generates its combinations with nested m4
macros. Kazakh stacks four — `мектеп-тер-іміз-де` — so the combinations have to
be generated, and this is the generator.

The cut is after the first morpheme. That one is the only suffix whose shape
the *stem* decides, so it goes in level one keyed on the stem's class; whatever
follows it is fixed by the morpheme before it, so the entire rest of the chain
can be one atomic string in level two. Depth stops mattering: `ларындағылардың`
is five morphemes and still only two levels.

    python tools/gen_aff.py -o dict/kk_KZ.aff
    python tools/gen_aff.py --check dict/kk_KZ.aff    # for CI

Reads data/residues.tsv, which is committed, and the layer model from
kazsearch-py, which is needed only to know where one morpheme ends.
"""

from __future__ import annotations

import argparse
import collections
import difflib
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from kkphon import CLASSES  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_KAZSEARCH = Path(os.environ.get("KAZSEARCH_SRC", ROOT.parent / "kazsearch-py"))

RULE_TABLES = ("PRED_RULES", "CASE_RULES", "POSS_RULES", "PLUR_RULES", "DERIV_RULES",
               "VPERSON_RULES", "VTENSE_RULES", "VNEG_RULES", "VVOICE_RULES")

# Flags are numeric because there are several hundred and single-character
# flags run out at about 64 — the wall the 2009 file was already against, with
# 51 of them used.
CLASS_FLAG = {cls: 10 + i for i, cls in enumerate(CLASSES)}
CONT_FLAG_BASE = 100

HEADER = """\
# Kazakh affix file, generated by tools/gen_aff.py — do not edit by hand.
#
# Suffix shape is decided by two things: vowel harmony, from the last vowel of
# the stem, and the stem's final segment. Both are settled once per entry and
# recorded in its flags, so no rule below has to re-derive them from a fixed
# window of the stem — which is what limited the 2009 file to stems with a
# vowel in the last two characters.
#
# Level one attaches the first morpheme and hands off a continuation flag.
# Level two carries the whole remainder of the chain as one string, so a form
# of any suffix depth still costs Hunspell only the two levels it strips.

SET UTF-8
FLAG num

TRY аеқыңғұрстізөүлйбоюпшнмәһджхцвчфъьэё

WORDCHARS -'’

# The pairs a Kazakh typist actually confuses: each letter Cyrillic added for
# Kazakh against its nearest Russian neighbour, which is what a keyboard left
# on the Russian layout produces.
MAP 8
MAP аә
MAP оө
MAP уұү
MAP ыі
MAP иі
MAP кқ
MAP гғ
MAP нң

# Same substitutions as an edit the suggester can undo, in the direction the
# mistake is made: the Russian letter was typed, the Kazakh one was meant.
REP 8
REP а ә
REP о ө
REP у ү
REP у ұ
REP и і
REP к қ
REP г ғ
REP н ң
"""


def morphemes(kazsearch: Path) -> set[str]:
    """Every suffix the layer model knows, as one flat set.

    Only the boundaries matter here. Which layer a morpheme belongs to decides
    what may follow it, and that question is already answered by the corpus:
    a residue is in the data because some Kazakh text contained it.
    """
    sys.path.insert(0, str(kazsearch / "src"))
    try:
        from kazsearch import rules
    except ImportError:
        sys.exit(f"no kazsearch under {kazsearch} — pass --kazsearch")
    return {r.suffix for table in RULE_TABLES for r in getattr(rules, table)}


def read_residues(path: Path) -> list[tuple[str, str, str, int]]:
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line and not line.startswith("#"):
            cls, strip, residue, count = line.split("\t")
            rows.append((cls, "" if strip == "0" else strip, residue, int(count)))
    return rows


# A stem-final voiceless stop voices before a vowel-initial suffix: `кітап` is
# `кітабы`. The rule has to strip the `п` and put `бы` on, and the plain rule
# for the same suffix has to be kept off those three letters, or the file also
# generates `*кітапы` — which is what it did while the miner sliced the form at
# the stem's length.
VOICING = {"қ": "ғ", "к": "г", "п": "б"}
UNVOICED = "[^" + "".join(sorted(VOICING)) + "]"


def split_first(residue: str, inventory: set[str]) -> tuple[str, str] | None:
    """Cut after the longest opening morpheme that leaves a segmentable tail.

    Longest-first matters. `лары` is a possessive in its own right, so cutting
    `ларында` after `лар` and after `лары` are both defensible; taking the
    longer one puts more of the chain in level one, where it is checked against
    the stem, and leaves less to the tail, where it is not.
    """
    for k in range(min(len(residue), 6), 0, -1):
        head = residue[:k]
        if head in inventory and _segmentable(residue[k:], inventory):
            return head, residue[k:]
    return None


def _segmentable(tail: str, inventory: set[str], _memo: dict[str, bool] = {}) -> bool:
    if not tail:
        return True
    if tail not in _memo:
        _memo[tail] = any(tail[:k] in inventory and _segmentable(tail[k:], inventory)
                          for k in range(1, len(tail) + 1))
    return _memo[tail]


# Consonants that alternate at the front of one and the same morpheme. Within
# a set the choice is not free: the stem decides it, and exactly one answer is
# right. `-дан` and `-тан` and `-нан` are the ablative in three shapes.
ALTERNATIONS = (frozenset("лдтн"), frozenset("ғқгк"), frozenset("бпм"))

# The harmony pairs, folded together for the same reason: `-дан` and `-ден` are
# one morpheme, so a class that takes one cannot also take the other, and they
# have to compete rather than each be counted on its own.
HARMONY_FOLD = str.maketrans("аәеоөұүыіи", "AAAOOUUIII")

# How far below the winning shape a rival may sit and still be believed. The
# corpus is dictionary text and carries a little noise — `айтды`, `атға`,
# `ақды` are all in it, once each — and without this a single such token
# licenses a whole wrong allomorph for every stem in the class.
MINORITY_SHARE = 0.35


def sibling_key(morpheme: str) -> tuple[str, str] | None:
    """What a morpheme is, with the shape its stem chose stripped off.

    `-дан`, `-ден`, `-тан`, `-тен`, `-нан` and `-нен` all reduce to the same
    key: one ablative, six shapes, of which a given stem licenses exactly one.
    """
    if not morpheme:
        return None
    for group in ALTERNATIONS:
        if morpheme[0] in group:
            return "".join(sorted(group)), morpheme[1:].translate(HARMONY_FOLD)
    return None


def winners(weight: collections.Counter, shape_of) -> set:
    """Drop entries whose shape lost badly to a sibling in the same context.

    Allomorph selection is deterministic: within one context a morpheme has a
    single correct shape and its siblings are errors. So rather than trusting
    every pairing the corpus offers, the shapes compete and the ones left far
    behind are dropped. Genuine ties survive — `-да` after a vowel-final stem
    and `-на` after a possessive both earn their place — since the test is
    relative, not absolute.

    `weight` is keyed on (context, morpheme); `shape_of` reduces a morpheme to
    what it would be in any shape.
    """
    best = collections.defaultdict(int)
    for (context, morpheme), count in weight.items():
        key = shape_of(morpheme)
        if key:
            best[context, key] = max(best[context, key], count)

    return {(context, morpheme) for (context, morpheme), count in weight.items()
            if not shape_of(morpheme)
            or count >= best[context, shape_of(morpheme)] * MINORITY_SHARE}


def build(rows, inventory):
    """(class → its level-one rules, continuation group → its level-two rules)."""
    def cont_key(cls: str, s1: str) -> tuple[str, str, str]:
        """What a level-two group is keyed on: track, harmony, opening morpheme.

        Harmony has to stay in the key because the tail agrees with the stem,
        not with the morpheme in front of it. The track has to stay because a
        noun and a verb take different things after the same-looking suffix.
        And the morpheme itself has to stay because what may follow `-лар` is
        not what may follow `-да`, even where both end in the same sound.
        """
        return cls[0], cls[1], s1

    def opening_morpheme(residue: str) -> str:
        cut = split_first(residue, inventory)
        return cut[0] if cut else residue

    split_rows, unsplit = [], []
    for cls, strip, residue, count in rows:
        cut = split_first(residue, inventory)
        if cut is None:
            unsplit.append((cls, residue))
        else:
            split_rows.append((cls, (strip, cut[0]), cut[1], count))

    opening = collections.Counter()
    for cls, s1, _tail, count in split_rows:
        opening[cls, s1] += count
    keep_opening = winners(opening, lambda s1: sibling_key(s1[1]))

    # The tail is voted on the same way, in the context of the morpheme it
    # follows. `-ның` after `-лар` and `-дың` after `-лар` cannot both be
    # right, and only one of them is `акциялардың`.
    following = collections.Counter()
    for cls, s1, tail, count in split_rows:
        if tail and (cls, s1) in keep_opening:
            following[cont_key(cls, s1), tail] += count
    keep_tail = winners(following, lambda tail: sibling_key(opening_morpheme(tail)))

    level1 = collections.defaultdict(dict)   # class -> {s1: continuation key or None}
    level2 = collections.defaultdict(set)    # (harmony, s1) -> {tails}
    rejected = 0

    for cls, s1, tail, _count in split_rows:
        if (cls, s1) not in keep_opening:
            rejected += 1
            continue
        key = cont_key(cls, s1)
        level1[cls].setdefault(s1, None)
        if tail:
            if (key, tail) not in keep_tail:
                rejected += 1
                continue
            level1[cls][s1] = key
            level2[key].add(tail)
    return level1, level2, unsplit, rejected


def render(level1, level2) -> str:
    cont_flag = {key: CONT_FLAG_BASE + i for i, key in enumerate(sorted(level2))}
    out = [HEADER]

    out.append("# Level one: the first morpheme, keyed on the stem's class.")
    for cls in CLASSES:
        rules = level1.get(cls)
        if not rules:
            continue
        flag = CLASS_FLAG[cls]
        voicing = {s1 for strip, s1 in rules if strip}
        out.append(f"\nSFX {flag} N {len(rules)}")
        for strip, s1 in sorted(rules):
            key = rules[strip, s1]
            body = (VOICING[strip] + s1) if strip else s1
            append = f"{body}/{cont_flag[key]}" if key else body
            # A plain rule for a suffix that is also known to voice has to be
            # kept off the three letters that voice, or the same suffix reaches
            # `кітап` twice and yields `*кітапы` alongside `кітабы`.
            condition = UNVOICED if not strip and s1 in voicing else "."
            out.append(f"SFX {flag} {strip or 0} {append} {condition}")

    out.append("\n# Level two: the rest of the chain, one string per attested form.")
    for key in sorted(level2):
        tails = sorted(level2[key])
        out.append(f"\nSFX {cont_flag[key]} N {len(tails)}")
        for tail in tails:
            out.append(f"SFX {cont_flag[key]} 0 {tail} .")

    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--output", type=Path)
    ap.add_argument("--check", type=Path, help="exit non-zero if this file is stale")
    ap.add_argument("--residues", type=Path, default=ROOT / "data/residues.tsv")
    ap.add_argument("--kazsearch", type=Path, default=DEFAULT_KAZSEARCH)
    args = ap.parse_args()

    rows = read_residues(args.residues)
    level1, level2, unsplit, rejected = build(rows, morphemes(args.kazsearch))
    text = render(level1, level2)

    n1 = sum(len(v) for v in level1.values())
    n2 = sum(len(v) for v in level2.values())
    print(f"{n1:,} level-one rules, {n2:,} level-two rules in "
          f"{len(level2):,} continuation groups", file=sys.stderr)
    print(f"{rejected:,} residues dropped as a minority allomorph, "
          f"{len(unsplit):,} with no morpheme boundary", file=sys.stderr)

    if args.check:
        current = args.check.read_text(encoding="utf-8")
        if current == text:
            print(f"{args.check}: up to date")
            return 0
        sys.stdout.writelines(difflib.unified_diff(
            current.splitlines(keepends=True), text.splitlines(keepends=True),
            fromfile=str(args.check), tofile="generated"))
        print(f"\n{args.check} is stale — regenerate it", file=sys.stderr)
        return 1

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8")
        print(f"wrote {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
