"""Collect the suffix strings Kazakh text actually puts on a stem.

The alternative is enumerating the layer model's cross-product, and it does not
survive contact with the arithmetic: the nominal chain alone is 45 × 6 × 24 ×
40 × 16 combinations, almost all of which no Kazakh speaker has ever uttered.
Mining instead gives a set that is both smaller and better targeted — 4,300
residues, of which the top 800 account for 92% of analysable forms.

Each residue is recorded against the *class* of stem it was seen on, because
that is what picks the suffix's shape: `-тар` after `мектеп`, `-дар` after
`жол`, `-лар` after `бала`. Taking the pairing from the corpus rather than
hand-writing an allomorph table is what keeps the 2009 file's half-typed
consonant lists from being reintroduced.

    python tools/mine_residues.py -o data/residues.tsv

The output is committed so that generating the affix file needs only this
repository; regenerating it needs a corpus and a checkout of kazsearch-py.
"""

from __future__ import annotations

import argparse
import collections
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from kkphon import stem_class  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_KAZSEARCH = Path(os.environ.get("KAZSEARCH_SRC", ROOT.parent / "kazsearch-py"))

UNCAPPED = 1024


def headwords(dic: Path) -> set[str]:
    return {line.split("/")[0].strip().lower()
            for line in dic.read_text(encoding="utf-8-sig").splitlines()[1:]
            if line.strip()}


def mine(corpus: list[str], heads: set[str], ladder) -> collections.Counter:
    """(stem class, residue) → how many corpus forms it explains.

    The *shortest* headword on the ladder wins, so a form is charged to the
    longest suffix string that reaches a known stem. Taking the longest
    headword instead would credit `мектептер` to `мектептер` whenever that had
    been entered as a headword in its own right, and the 2009 wordlist is full
    of those — which is precisely the padding this is meant to see past.
    """
    counts = collections.Counter()
    for word in corpus:
        low = word.lower()
        stem = None
        for rung in ladder(low, max_rungs=UNCAPPED):
            if rung in heads and (stem is None or len(rung) < len(stem)):
                stem = rung
        if stem is None or stem == low:
            continue
        counts[stem_class(stem), low[len(stem):]] += 1
    return counts


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--output", type=Path, default=ROOT / "data/residues.tsv")
    ap.add_argument("--corpus", type=Path, default=ROOT / "tests/corpus_cyr.txt")
    ap.add_argument("--dic", type=Path, default=ROOT / "baseline/kk_KZ.dic")
    ap.add_argument("--kazsearch", type=Path, default=DEFAULT_KAZSEARCH)
    ap.add_argument("--min-count", type=int, default=2,
                    help="drop residues seen once; at that frequency a stemmer "
                         "misanalysis is as likely as a real suffix")
    args = ap.parse_args()

    if not args.corpus.exists():
        sys.exit(f"no corpus at {args.corpus} — run `make baseline` first")
    sys.path.insert(0, str(args.kazsearch / "src"))
    try:
        from kazsearch.ladder import ladder
    except ImportError:
        sys.exit(f"no kazsearch under {args.kazsearch} — pass --kazsearch")

    counts = mine(args.corpus.read_text(encoding="utf-8").split(),
                  headwords(args.dic), ladder)

    rows = sorted(((n, c, r) for (c, r), n in counts.items() if n >= args.min_count),
                  key=lambda row: (-row[0], row[1], row[2]))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as fh:
        fh.write("# class\tresidue\tcount — generated by tools/mine_residues.py\n")
        for n, cls, residue in rows:
            fh.write(f"{cls}\t{residue}\t{n}\n")

    kept = sum(n for n, _, _ in rows)
    print(f"{len(rows):,} (class, residue) pairs over {kept:,} forms "
          f"→ {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
