"""Find the elements Kazakh actually builds compounds from.

Kazakh compounds are mostly lexicalised — written solid and listed in
dictionaries — so most of them belong in the wordlist rather than in a rule.
The exception is a set of bound international prefixes, `авто-`, `агро-`,
`теле-`, `микро-`, which attach to more or less any noun and cannot all be
listed. Those are what `COMPOUNDBEGIN` is for.

The candidates are found by looking for headwords that are exactly two other
headwords, then grouping by first element. That turns up three kinds of thing
and only one of them is wanted:

    авто, гидро, радио, микро    bound prefixes, productive        — wanted
    қара, қызыл, түйе, бала      native words in lexicalised pairs — listed already
    гуль, әбді, сейт, мырза      name components: сейталиев        — not compounds

The last kind is excluded by asking what an element mostly produces. If its
products are mostly names, it is a name component, whatever it looks like.

    python tools/mine_compounds.py -o data/compounds.txt
"""

from __future__ import annotations

import argparse
import collections
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from gen_dic import read_lexicon  # noqa: E402
from measure_running import tokens  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent

MIN_PART = 4


def lexicalised(lexicon: set[str]) -> dict[str, set[str]]:
    """First element → the headwords it appears to open."""
    out: dict[str, set[str]] = collections.defaultdict(set)
    for word in lexicon:
        if len(word) < MIN_PART * 2:
            continue
        for cut in range(MIN_PART, len(word) - MIN_PART + 1):
            if word[:cut] in lexicon and word[cut:] in lexicon:
                out[word[:cut]].add(word)
                break
    return out


def read_names(*paths: Path) -> set[str]:
    names: set[str] = set()
    for path in paths:
        if path.exists():
            names |= {line.strip() for line in path.read_text(encoding="utf-8").splitlines()
                      if line.strip() and not line.startswith("#")}
    return names


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--output", type=Path, default=ROOT / "data/compounds.txt")
    ap.add_argument("--lexicon", type=Path, default=ROOT / "data/lexicon.tsv")
    ap.add_argument("--min-products", type=int, default=12,
                    help="compounds an element must form to count as productive")
    ap.add_argument("--max-name-share", type=float, default=0.34,
                    help="above this the element is building names, not compounds")
    ap.add_argument("--kaznerd", type=Path, default=ROOT.parent / "KazNERD/KazNERD")
    ap.add_argument("--max-standalone", type=int, default=30,
                    help="an element seen this often on its own is an ordinary "
                         "word, not a bound prefix: its compounds are "
                         "lexicalised and already in the wordlist")
    args = ap.parse_args()

    lexicon = set(read_lexicon(args.lexicon))
    names = read_names(ROOT / "data/names.txt", ROOT / "data/names_wp.txt")

    # `авто-` and `агро-` hardly ever stand alone; `қара` and `бала` are
    # everyday words. Only the first kind is productive — the compounds of the
    # second kind are lexicalised, already listed, and letting them combine
    # freely buys `автоалма` and `телебала`.
    standalone = tokens(args.kaznerd, "train") if args.kaznerd.exists() else {}

    kept, rejected, ordinary = [], [], []
    for element, products in lexicalised(lexicon).items():
        if len(products) < args.min_products:
            continue
        share = sum(1 for w in products if w in names) / len(products)
        seen = standalone.get(element, 0) + standalone.get(element.capitalize(), 0)
        if share > args.max_name_share:
            rejected.append((len(products), element, share))
        elif seen > args.max_standalone:
            ordinary.append((len(products), element, seen))
        else:
            kept.append((len(products), element, share))

    kept.sort(key=lambda row: -row[0])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "# elements that open compounds, generated by tools/mine_compounds.py\n"
        + "\n".join(element for _n, element, _s in sorted(kept, key=lambda r: r[1]))
        + "\n", encoding="utf-8")

    print(f"{len(kept):,} compound-forming elements → {args.output}", file=sys.stderr)
    print(f"{len(ordinary):,} rejected as ordinary words: "
          f"{', '.join(e for _n, e, _s in sorted(ordinary, key=lambda r: -r[0])[:8])}",
          file=sys.stderr)
    print(f"{len(rejected):,} rejected as name components: "
          f"{', '.join(e for _n, e, _s in sorted(rejected, key=lambda r: -r[0])[:8])}",
          file=sys.stderr)
    print("  most productive: "
          + ", ".join(f"{e} ({n})" for n, e, _s in kept[:12]), file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
