"""Work out which headwords the affix file has made unnecessary.

The 2009 wordlist enters inflected forms as headwords in their own right —
`абай`, `абайдан` and `абайдың` are three of its 54,063 entries. That padding
was how a one-suffix affix file coped. It is not free now: an inflected form
entered as a stem gets a class flag of its own, and suffixes then stack on top
of an already-inflected word, which is where `*аккумуляторыдың` comes from.

Deciding what is safe to drop takes two passes, both empirical.

**Redundant.** Build the dictionary without every candidate at once and keep
back whatever Hunspell then rejects. Removing them together is the conservative
direction — a word only goes if it survives the removal of everything else that
might have explained it — and it keeps derivations like `абайсыздық`, which the
ladder cannot tell from an inflection but the rules cannot produce.

**Load-bearing.** A regenerable headword can still be the stem of something
longer: dropping all 21,494 costs 20,170 corpus forms, because the affix file
only knows the suffix strings that were mined against the stems it had. Those
5,451 entries come back.

    python tools/prune.py -o data/prune.txt

The result is committed so that building the dictionary needs only this
repository; recomputing it needs a corpus, kazsearch-py and hunspell.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from gen_dic import entry, read_wordlist  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_KAZSEARCH = Path(os.environ.get("KAZSEARCH_SRC", ROOT.parent / "kazsearch-py"))

UNCAPPED = 1024


def spell(aff: Path, words: list[str], probe: list[str]) -> set[str]:
    """Which of `probe` a dictionary of exactly `words` rejects."""
    with tempfile.TemporaryDirectory() as tmp:
        base = Path(tmp) / "trial"
        base.with_suffix(".aff").write_bytes(aff.read_bytes())
        base.with_suffix(".dic").write_text(
            f"{len(words)}\n" + "\n".join(sorted(entry(w) for w in words)) + "\n",
            encoding="utf-8")
        proc = subprocess.run(["hunspell", "-d", str(base), "-l"],
                              input="\n".join(probe), capture_output=True, text=True)
    if proc.returncode != 0:
        sys.exit(f"hunspell failed: {proc.stderr.strip()}")
    return set(proc.stdout.split())


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--output", type=Path, default=ROOT / "data/prune.txt")
    ap.add_argument("--source", type=Path, default=ROOT / "baseline/kk_KZ.dic")
    ap.add_argument("--aff", type=Path, default=ROOT / "dict/kk_KZ.aff")
    ap.add_argument("--corpus", type=Path, default=ROOT / "tests/corpus_cyr.txt")
    ap.add_argument("--kazsearch", type=Path, default=DEFAULT_KAZSEARCH)
    args = ap.parse_args()

    if not args.corpus.exists():
        sys.exit(f"no corpus at {args.corpus} — run `make baseline` first")
    sys.path.insert(0, str(args.kazsearch / "src"))
    try:
        from kazsearch.ladder import ladder
    except ImportError:
        sys.exit(f"no kazsearch under {args.kazsearch} — pass --kazsearch")

    words = read_wordlist(args.source)
    lowered = {w.lower() for w in words}
    candidates = {w for w in words
                  if any(rung in lowered and rung != w.lower()
                         for rung in ladder(w.lower(), max_rungs=UNCAPPED))}

    keep = [w for w in words if w not in candidates]
    redundant = candidates - spell(args.aff, keep, sorted(candidates))
    print(f"{len(candidates):,} candidates, {len(redundant):,} regenerable",
          file=sys.stderr)

    corpus = args.corpus.read_text(encoding="utf-8").split()
    lost = (spell(args.aff, [w for w in words if w not in redundant], corpus)
            - spell(args.aff, words, corpus))
    by_form = {w.lower(): w for w in redundant}
    load_bearing = {by_form[rung] for form in lost
                    for rung in ladder(form.lower(), max_rungs=UNCAPPED)
                    if rung in by_form}
    print(f"{len(lost):,} forms would be lost; {len(load_bearing):,} entries stay",
          file=sys.stderr)

    drop = sorted(redundant - load_bearing)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "# headwords the affix file regenerates, generated by tools/prune.py\n"
        + "\n".join(drop) + "\n", encoding="utf-8")
    print(f"{len(drop):,} headwords → {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
