"""Build the misspellings people actually make, and see if they are caught.

`tools/negatives.py` corrupts a word's *suffix* — `-лар` for `-лер` — which is
a linguist's error. Nobody types `мектептар`. It measures whether the affix
rules are too loose, which is worth knowing and is not the same question as
whether the dictionary does its job.

A spellchecker exists to catch mistakes, and the mistakes are keyboard slips
and letter confusions. Kazakh has a particular one: the nine letters Cyrillic
added for it sit next to their Russian neighbours on the keyboard and in the
mind, so `қ` for `к` and `ә` for `а` are the errors of the language. Those are
also exactly what the `MAP` and `REP` tables in the affix file exist to undo,
which nothing has ever checked.

    python tools/typos.py --write tests/typos.txt
    python tools/typos.py dict/kk_KZ baseline/kk_KZ

A dictionary that accepts a typo has failed silently, which is the failure a
user cannot see. A dictionary that flags a correct word has failed loudly,
which they can.
"""

from __future__ import annotations

import argparse
import random
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The letters Kazakh added to Cyrillic, against what a Russian keyboard or a
# hurried hand puts there instead. These are the characteristic misspellings.
CONFUSIONS = [("ә", "а"), ("ө", "о"), ("ұ", "у"), ("ү", "у"), ("і", "и"),
              ("қ", "к"), ("ғ", "г"), ("ң", "н"), ("һ", "х")]

# ЙЦУКЕН, the layout Kazakh is typed on, row by row. Neighbours on a row are
# the keys a slipping finger reaches.
ROWS = ["йцукенгшщзхъ", "фывапролджэ", "ячсмитьбю"]


def neighbours() -> dict[str, str]:
    out: dict[str, str] = {}
    for row in ROWS:
        for i, ch in enumerate(row):
            out[ch] = row[max(0, i - 1):i] + row[i + 1:i + 2]
    return out


def typos(word: str, keys: dict[str, str]) -> list[tuple[str, str]]:
    """(kind, misspelling) for one word."""
    out = []
    for i, ch in enumerate(word):
        for a, b in CONFUSIONS:
            if ch == a:
                out.append(("confusion", word[:i] + b + word[i + 1:]))
            elif ch == b:
                out.append(("confusion", word[:i] + a + word[i + 1:]))
        for near in keys.get(ch, ""):
            out.append(("keyboard", word[:i] + near + word[i + 1:]))
        out.append(("doubled", word[:i] + ch + word[i:]))
        if len(word) > 3:
            out.append(("dropped", word[:i] + word[i + 1:]))
        if i + 1 < len(word) and word[i] != word[i + 1]:
            out.append(("swapped", word[:i] + word[i + 1] + word[i] + word[i + 2:]))
    return out


def build(corpus: list[str], limit: int, seed: int = 0) -> list[tuple[str, str, str]]:
    """(kind, original, misspelling), excluding any that is itself a real word."""
    real = set(corpus) | {w.lower() for w in corpus}
    keys = neighbours()
    rng = random.Random(seed)
    words = [w.lower() for w in corpus if len(w) > 3]
    rng.shuffle(words)

    seen, out = set(), []
    for word in words:
        for kind, bad in typos(word, keys):
            if bad not in real and bad not in seen and bad != word:
                seen.add(bad)
                out.append((kind, word, bad))
        if len(out) >= limit * 3:
            break
    rng.shuffle(out)
    return out[:limit]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dictionaries", type=Path, nargs="*")
    ap.add_argument("--corpus", type=Path, default=ROOT / "tests/corpus_cyr.txt")
    ap.add_argument("--write", type=Path)
    ap.add_argument("--limit", type=int, default=40_000)
    args = ap.parse_args()

    if not args.corpus.exists():
        sys.exit(f"no corpus at {args.corpus} — run `make baseline` first")
    cases = build(args.corpus.read_text(encoding="utf-8").split(), args.limit)

    if args.write:
        args.write.write_text(
            "# kind\toriginal\tmisspelling — generated by tools/typos.py\n"
            + "\n".join(f"{k}\t{o}\t{b}" for k, o, b in cases) + "\n",
            encoding="utf-8")
        print(f"{len(cases):,} misspellings → {args.write}", file=sys.stderr)

    for base in args.dictionaries:
        bad = [b for _k, _o, b in cases]
        proc = subprocess.run(["hunspell", "-d", str(base), "-l"],
                              input="\n".join(bad), capture_output=True, text=True)
        flagged = set(proc.stdout.split())
        missed = [(k, o, b) for k, o, b in cases if b not in flagged]
        print(f"\n{base}: catches {len(cases) - len(missed):,}/{len(cases):,} "
              f"({(1 - len(missed) / len(cases)) * 100:.1f}%)")
        by_kind: dict[str, list[int]] = {}
        for kind, _o, bad_word in cases:
            row = by_kind.setdefault(kind, [0, 0])
            row[1] += 1
            if bad_word in flagged:
                row[0] += 1
        for kind, (caught, total) in sorted(by_kind.items()):
            print(f"  {kind:<10} {caught / total * 100:5.1f}%  ({caught:,}/{total:,})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
